apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-workers
  namespace: judge-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: judge-workers
  template:
    metadata:
      labels:
        app: judge-workers
    spec:
      containers:
        - name: judge-worker
          image: lightningsagar/worker:fd20b1a49c1cdedd11364fb962915df9ee7f6942
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "3000"
            - name: host_redis
              value: "redis-0.redis.judge-namespace.svc.cluster.local"
            - name: password_redis
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"

          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "g++ --version"]
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 5
        - name: 
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: judge-namespace
type: Opaque
data:
  password: bTBseE1LUUx0MjFOcWtlUXk2RWNrWEFaRUZCWUU5RXM= # base64 of "m0lxMKQLt21NqkeQy6EckxAZEFBYE9Es"
