apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-workers
  namespace: judge-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: judge-workers
  template:
    metadata:
      labels:
        app: judge-workers
    spec:
      containers:
        - name: judge-worker
          image: lightningsagar/worker:0c7713f837fe5b44c08de3387b6f3b9c5c0feede
          ports:
            - containerPort: 5000
          env:
            - name: WORKER_FIELD
              value: "worker_0"
            - name: PORT
              value: "5000"
            - name: host_redis
              value: "host_redis"
            - name: password_redis
              value: "password_redis"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "g++ --version"]
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-service
  namespace: judge-namespace
spec:
  type: NodePort
  selector:
    app: judge-workers
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: judge-workers-hpa
  namespace: judge-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: judge-workers
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70