apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-workers
  namespace: judge-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: judge-workers
  template:
    metadata:
      labels:
        app: judge-workers
    spec:
      containers:
        - name: judge-worker
          image: lightningsagar/worker:fd20b1a49c1cdedd11364fb962915df9ee7f6942
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '3000'
            - name: host_redis
              value: 'redis-10605.c81.us-east-1-2.ec2.redns.redis-cloud.com'
            - name: password_redis
              value: 'm0lxMKQLt21NqkeQy6EckxAZEFBYE9Es'
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "2000m"
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "g++ --version"]
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: cpu-service
  namespace: judge-namespace
spec:
  type: NodePort
  selector:
    app: judge-workers
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: judge-workers-hpa
  namespace: judge-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: judge-workers
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70