apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: judge-namespace
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          command: ["redis-server", "--appendonly", "yes", "--requirepass", "m0lxMKQLt21NqkeQy6EckxAZEFBYE9Es"]
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: judge-namespace
spec:
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None # Required for StatefulSets (headless service)
  selector:
    app: redis
