name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Clone Judge Repo
        run: |
          git clone https://github.com/lightning-sagar/Judge.git
          cd Judge/lib
          ls

      - name: Update Package Version (Patch)
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        run: |
          cd Judge/lib
          npm version patch
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "chore: bump patch version [skip ci]"
          git push https://${GITHUB_PAT}@github.com/lightning-sagar/Judge.git main

      - name: Publish Package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd Judge/lib
          npm publish
